### ISSUE TITLE
Layers Showcase Image error

### ISSUE THREAD

**Issue by bilalmirza74** [TrevorBlythe/swagNeuralNet#4]
![Screenshot 2023-09-07 081938](https://github.com/TrevorBlythe/MentisJS/assets/84387676/8f35ff47-da21-4e0e-8209-1eea4483fcd1)

**Comment by TrevorBlythe** [comment]
thats not a glitch i just dont know what image to put there lol

**Comment by TrevorBlythe** [comment]
Thanks I added your image! I put your name in the commit. Also made me see the fatal relu error i made earlier and fixed that to.
